### ISSUE TITLE
'proj' keyword error

### ISSUE THREAD

**Issue by ashtonflinders** [SCECcode/UCVM#21]
Trying to setup on linux, getting the following errors;

Downloading CCA...
Extracting CCA...
Installing CCA...
    Moving model data to directory...
Traceback (most recent call last):
  File "/home/ashton/Treetop/PROJECTS/LVC_2016/ucvm-17.2.0/lib/python3.5/site-packages/ucvm-17.2.0-py3.5.egg/EGG-INFO/scripts/ucvm_run_tests", line 104, in <module>
    sys.exit(main())
  File "/home/ashton/Treetop/PROJECTS/LVC_2016/ucvm-17.2.0/lib/python3.5/site-packages/ucvm-17.2.0-py3.5.egg/EGG-INFO/scripts/ucvm_run_tests", line 67, in main
    model = UCVM.get_model_instance(options["model"])
  File "/home/ashton/Treetop/PROJECTS/LVC_2016/ucvm-17.2.0/lib/python3.5/site-packages/ucvm-17.2.0-py3.5.egg/ucvm/src/framework/ucvm.py", line 202, in get_model_instance
    UCVM.instantiated_models[model] = getattr(new_class, found["class"])()
  File "/home/ashton/Treetop/PROJECTS/LVC_2016/ucvm-17.2.0/lib/python3.5/site-packages/ucvm-17.2.0-py3.5.egg/ucvm/src/model/velocity/gridded_velocity_model.py", line 103, in __init__
    self.out_proj = pyproj.Proj(self.config_dict["proj"])
KeyError: 'proj'

any clue?

**Comment by scecdavid** [comment]
This is fixed in the development branch and will be merged into master shortly.
