### ISSUE TITLE
basin branch testing

### ISSUE THREAD

**Issue by pjmaechling** [SCECcode/UCVM#22]
error running check_files_md5.py

Checking file: cvmhvbn.tar.gz
Traceback (most recent call last):
  File "./check_largefiles_md5.py", line 99, in <module>
    total_ok, total_errs = check_md5file(model,fp.name,total_ok,total_errs)
  File "./check_largefiles_md5.py", line 72, in check_md5file
    if res[1].decode("utf-8") == "OK":
IndexError: list index out of range

**Comment by meihuisu** [comment]
fix typo in setup/setup.list
