### ISSUE TITLE
usc installation issue

### ISSUE THREAD

**Issue by pjmaechling** [SCECcode/UCVM#62]
Error using python 3.6 installation on HPC. Will retry using Python 3.5

===
Writing /home/scec-00/maechlin/u1/lib/python3.6/site-packages/ucvm_c_common-0.0.0-py3.6.egg-info
	Done!

Downloading 1D...
Extracting 1D...
Installing 1D...
    Moving model data to directory...
Running tests for 1D...
Testing 1D...
    [1 test]
    [001] Running 1D BBP format test...                     
======================================================================
ERROR: test_onedimensional_bbp_depth (ucvm.models.1d.test_1d.OneDimensionalVelocityModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/scec-00/maechlin/u1/lib/python3.6/site-packages/ucvm-17.3.0-py3.6.egg/ucvm/models/1d/test_1d.py", line 56, in test_onedimensional_bbp_depth
    UCVM.query(self.data["depth"], "1d[CyberShake_BBP_LA_Basin]", ["velocity"])
  File "/home/scec-00/maechlin/u1/lib/python3.6/site-packages/ucvm-17.3.0-py3.6.egg/ucvm/src/framework/ucvm.py", line 169, in query
    points, params=model_to_query[1]
  File "/home/scec-00/maechlin/u1/lib/python3.6/site-packages/ucvm-17.3.0-py3.6.egg/ucvm/src/model/model.py", line 145, in query
    if not isinstance(data, List[SeismicData]):
  File "/home/scec-00/maechlin/anaconda3/lib/python3.6/typing.py", line 1070, in __instancecheck__
    return issubclass(instance.__class__, self)
  File "/home/scec-00/maechlin/anaconda3/lib/python3.6/abc.py", line 207, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
  File "/home/scec-00/maechlin/anaconda3/lib/python3.6/typing.py", line 866, in __extrahook__
    _valid_for_check(cls)
  File "/home/scec-00/maechlin/anaconda3/lib/python3.6/typing.py", line 837, in _valid_for_check
    raise TypeError("Parameterized generics cannot be used with class "
TypeError: Parameterized generics cannot be used with class or instance checks

----------------------------------------------------------------------
Ran 1 test in 0.062s

FAILED (errors=1)

Downloading USGS/NOAA Digital Elevation Model...

**Comment by breuera** [comment]
Having the same issue with the most recent python version (don't think its HPC-related)
```
(ucvm-17.3.0) -bash-4.2$ python --version
Python 3.6.3
```

```
[...]
Running tests for 1D...
Testing 1D...
    [1 test]
    [001] Running 1D BBP format test...                     
======================================================================
ERROR: test_onedimensional_bbp_depth (ucvm.models.1d.test_1d.OneDimensionalVelocityModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/breuera/software/ucvm-17.3.0/lib/python3.6/site-packages/ucvm-17.3.0-py3.6.egg/ucvm/models/1d/test_1d.py", line 56, in test_onedimensional_bbp_depth
    UCVM.query(self.data["depth"], "1d[CyberShake_BBP_LA_Basin]", ["velocity"])
  File "/home/breuera/software/ucvm-17.3.0/lib/python3.6/site-packages/ucvm-17.3.0-py3.6.egg/ucvm/src/framework/ucvm.py", line 169, in query
    points, params=model_to_query[1]
  File "/home/breuera/software/ucvm-17.3.0/lib/python3.6/site-packages/ucvm-17.3.0-py3.6.egg/ucvm/src/model/model.py", line 145, in query
    if not isinstance(data, List[SeismicData]):
  File "/home/breuera/software/lib/python3.6/typing.py", line 1161, in __instancecheck__
    return issubclass(instance.__class__, self)
  File "/home/breuera/software/lib/python3.6/typing.py", line 1147, in __subclasscheck__
    raise TypeError("Parameterized generics cannot be used with class "
TypeError: Parameterized generics cannot be used with class or instance checks

----------------------------------------------------------------------
Ran 1 test in 0.014s

FAILED (errors=1)
[...]
```

Function seems to be deprecated the way it is used: https://github.com/python/typing/issues/136

Since this seems to be a safety check, I simply commented lines 145 and 146:
https://github.com/SCECcode/UCVM/blob/716db787a1b5b444d791547eeca4e2a3ee613da1/ucvm/src/model/model.py#L145

That gets around the issue:
```
Downloading 1D...
Extracting 1D...
Installing 1D...
    Moving model data to directory...
Running tests for 1D...
Testing 1D...
    [1 test]
    [001] Running 1D BBP format test...                     
          PASSED
----------------------------------------------------------------------
Ran 1 test in 0.013s

OK
```
